variables:
    CI_IMAGE_TAG: "opengl"
    MODERNGL_DEBUGGING: "true"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
    ABSTRACTPLOTTING_MINIMAL: "false"

test:
    image: "juliagpu/julia:v1.3-${CI_IMAGE_TAG}"

    tags:
        - xorg
    cache:
        key: "hello" # fix this to refresh weekly later
        paths:
            - .julia/artifacts

    before_script:
        - apt-get -qq update
        # glfw
        - apt-get install -y cmake xorg-dev mesa-utils

    script:
      - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
      - julia -e 'using InteractiveUtils; versioninfo()'
      - julia --project -e 'using Pkg; Pkg.test(; coverage=true)'
      - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

    artifacts:
        when: on_failure
        paths:
        - test/tested_different
        - test/test_recordings
        - Project.toml
        - Manifest.toml
        expire_in: 2 day
