variables:
    CI_IMAGE_TAG: "opengl"
    MODERNGL_DEBUGGING: "true"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
    ABSTRACTPLOTTING_MINIMAL: "false"

test:
    image: "juliagpu/julia:v1.3-${CI_IMAGE_TAG}"
    tags:
        - xorg
    before_script:
        - apt-get -qq update
        # glfw
        - apt-get install -y cmake xorg-dev mesa-utils

    script:
      - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
      - julia -e 'using InteractiveUtils; versioninfo()'
      - mkdir temporary_for_project
      - julia --project=temporary_for_project -e 'using Pkg; Pkg.pkg"dev --local .; add StatsMakie#master MakieGallery#master GLMakie#master; test AbstractPlotting"'

    artifacts:
        when: on_failure
        paths:
        - test/tested_different
        - test/test_recordings
        expire_in: 2 day
