variables:
    CI_IMAGE_TAG: "opengl"
    MODERNGL_DEBUGGING: "true"
    JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia/"
    ABSTRACTPLOTTING_MINIMAL: "false"

test:
    image: "juliagpu/julia:v1.1-${CI_IMAGE_TAG}"
    before_script:
        - apt-get -qq update
        # glfw
        - apt-get install -y cmake xorg-dev mesa-utils

    script:
      - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
      - glxinfo | grep 'version'
      - julia -e 'using InteractiveUtils; versioninfo()'
      - julia --project -e 'using Pkg; Pkg.pkg"add Makie#master StatsMakie#master MakieGallery#master GLMakie#master; test"'

    artifacts:
        when: on_failure
        paths:
        - test/tested_different
        - test/test_recordings
        expire_in: 2 day
