## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 1

# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
    - julia: 1.3

script:
  - mkdir temporary_for_project # https://github.com/JuliaLang/Pkg.jl/pull/1696
  - export JL_PKG=AbstractPlotting
  - julia --project=temporary_for_project --color=yes -e "using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end; pkg\"dev --local .; add MakieGallery#master\""
  - julia --project=temporary_for_project --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(\"${JL_PKG}\"; coverage=true)"



## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("AbstractPlotting"); Pkg.test("AbstractPlotting"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("AbstractPlotting")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("AbstractPlotting")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
